// This file is generated by kconfig_compiler_kf5 from muon.kcfg.
// All changes you do to this file will be lost.

#include "MuonSettings.h"

#include <qglobal.h>
#include <QFile>

class MuonSettingsHelper
{
  public:
    MuonSettingsHelper() : q(nullptr) {}
    ~MuonSettingsHelper() { delete q; q = nullptr; }
    MuonSettingsHelper(const MuonSettingsHelper&) = delete;
    MuonSettingsHelper& operator=(const MuonSettingsHelper&) = delete;
    MuonSettings *q;
};
Q_GLOBAL_STATIC(MuonSettingsHelper, s_globalMuonSettings)
MuonSettings *MuonSettings::self()
{
  if (!s_globalMuonSettings()->q) {
    new MuonSettings;
    s_globalMuonSettings()->q->read();
  }

  return s_globalMuonSettings()->q;
}

MuonSettings::MuonSettings( )
  : KConfigSkeleton( QStringLiteral( "kydrarc" ) )
{
  Q_ASSERT(!s_globalMuonSettings()->q);
  s_globalMuonSettings()->q = this;
  setCurrentGroup( QStringLiteral( "muon" ) );

  QList<int> defaultSplitterSizes;

  KConfigSkeleton::ItemIntList  *itemSplitterSizes;
  itemSplitterSizes = new KConfigSkeleton::ItemIntList( currentGroup(), QStringLiteral( "SplitterSizes" ), mSplitterSizes, defaultSplitterSizes );
  addItem( itemSplitterSizes, QStringLiteral( "SplitterSizes" ) );
  KConfigSkeleton::ItemInt  *itemWidth;
  itemWidth = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "Width" ), mWidth, 600 );
  addItem( itemWidth, QStringLiteral( "Width" ) );
  KConfigSkeleton::ItemInt  *itemHeight;
  itemHeight = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "Height" ), mHeight, 400 );
  addItem( itemHeight, QStringLiteral( "Height" ) );
  KConfigSkeleton::ItemInt  *itemUndoStackSize;
  itemUndoStackSize = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "UndoStackSize" ), mUndoStackSize, 20 );
  addItem( itemUndoStackSize, QStringLiteral( "UndoStackSize" ) );
  KConfigSkeleton::ItemBool  *itemAskChanges;
  itemAskChanges = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "AskChanges" ), mAskChanges, true );
  addItem( itemAskChanges, QStringLiteral( "AskChanges" ) );
  KConfigSkeleton::ItemBool  *itemShowMultiArchDupes;
  itemShowMultiArchDupes = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowMultiArchDupes" ), mShowMultiArchDupes, false );
  addItem( itemShowMultiArchDupes, QStringLiteral( "ShowMultiArchDupes" ) );
  KConfigSkeleton::ItemString  *itemManagerListColumns;
  itemManagerListColumns = new KConfigSkeleton::ItemString( currentGroup(), QStringLiteral( "ManagerListColumns" ), mManagerListColumns );
  addItem( itemManagerListColumns, QStringLiteral( "ManagerListColumns" ) );
  KConfigSkeleton::ItemString  *itemReviewListColumns;
  itemReviewListColumns = new KConfigSkeleton::ItemString( currentGroup(), QStringLiteral( "ReviewListColumns" ), mReviewListColumns );
  addItem( itemReviewListColumns, QStringLiteral( "ReviewListColumns" ) );
  KConfigSkeleton::ItemBool  *itemUseSlowSearch;
  itemUseSlowSearch = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "UseSlowSearch" ), mUseSlowSearch, true );
  addItem( itemUseSlowSearch, QStringLiteral( "UseSlowSearch" ) );
  KConfigSkeleton::ItemBool  *itemConfirmOnQuit;
  itemConfirmOnQuit = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ConfirmOnQuit" ), mConfirmOnQuit, true );
  addItem( itemConfirmOnQuit, QStringLiteral( "ConfirmOnQuit" ) );
  KConfigSkeleton::ItemString  *itemStatusColumnColors;
  itemStatusColumnColors = new KConfigSkeleton::ItemString( currentGroup(), QStringLiteral( "StatusColumnColors" ), mStatusColumnColors );
  addItem( itemStatusColumnColors, QStringLiteral( "StatusColumnColors" ) );
  KConfigSkeleton::ItemBool  *itemShowVersionColumns;
  itemShowVersionColumns = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowVersionColumns" ), mShowVersionColumns, false );
  addItem( itemShowVersionColumns, QStringLiteral( "ShowVersionColumns" ) );
  KConfigSkeleton::ItemString  *itemLocalDebFolder;
  itemLocalDebFolder = new KConfigSkeleton::ItemString( currentGroup(), QStringLiteral( "LocalDebFolder" ), mLocalDebFolder );
  addItem( itemLocalDebFolder, QStringLiteral( "LocalDebFolder" ) );
  KConfigSkeleton::ItemStringList  *itemRepositories;
  itemRepositories = new KConfigSkeleton::ItemStringList( currentGroup(), QStringLiteral( "Repositories" ), mRepositories );
  addItem( itemRepositories, QStringLiteral( "Repositories" ) );
}

MuonSettings::~MuonSettings()
{
  if (s_globalMuonSettings.exists() && !s_globalMuonSettings.isDestroyed()) {
    s_globalMuonSettings()->q = nullptr;
  }
}

