// This file is generated by kconfig_compiler_kf5 from muon.kcfg.
// All changes you do to this file will be lost.
#ifndef MUONSETTINGS_H
#define MUONSETTINGS_H

#include <kconfigskeleton.h>
#include <QCoreApplication>
#include <QDebug>

class MuonSettings : public KConfigSkeleton
{
  public:

    static MuonSettings *self();
    ~MuonSettings() override;

    /**
      Set How the main window is divided.
    */
    static
    void setSplitterSizes( const QList<int> & v )
    {
      if (!self()->isSplitterSizesImmutable())
        self()->mSplitterSizes = v;
    }

    /**
      Get How the main window is divided.
    */
    static
    QList<int> splitterSizes()
    {
      return self()->mSplitterSizes;
    }

    /**
      Is How the main window is divided. Immutable
    */
    static
    bool isSplitterSizesImmutable()
    {
      return self()->isImmutable( QStringLiteral( "SplitterSizes" ) );
    }

    /**
      Set Width of the main window.
    */
    static
    void setWidth( int v )
    {
      if (!self()->isWidthImmutable())
        self()->mWidth = v;
    }

    /**
      Get Width of the main window.
    */
    static
    int width()
    {
      return self()->mWidth;
    }

    /**
      Is Width of the main window. Immutable
    */
    static
    bool isWidthImmutable()
    {
      return self()->isImmutable( QStringLiteral( "Width" ) );
    }

    /**
      Set Height of the main window.
    */
    static
    void setHeight( int v )
    {
      if (!self()->isHeightImmutable())
        self()->mHeight = v;
    }

    /**
      Get Height of the main window.
    */
    static
    int height()
    {
      return self()->mHeight;
    }

    /**
      Is Height of the main window. Immutable
    */
    static
    bool isHeightImmutable()
    {
      return self()->isImmutable( QStringLiteral( "Height" ) );
    }

    /**
      Set The amount of history kept for undo/redo.
    */
    static
    void setUndoStackSize( int v )
    {
      if (!self()->isUndoStackSizeImmutable())
        self()->mUndoStackSize = v;
    }

    /**
      Get The amount of history kept for undo/redo.
    */
    static
    int undoStackSize()
    {
      return self()->mUndoStackSize;
    }

    /**
      Is The amount of history kept for undo/redo. Immutable
    */
    static
    bool isUndoStackSizeImmutable()
    {
      return self()->isImmutable( QStringLiteral( "UndoStackSize" ) );
    }

    /**
      Set Whether or not to confirm additional changes.
    */
    static
    void setAskChanges( bool v )
    {
      if (!self()->isAskChangesImmutable())
        self()->mAskChanges = v;
    }

    /**
      Get Whether or not to confirm additional changes.
    */
    static
    bool askChanges()
    {
      return self()->mAskChanges;
    }

    /**
      Is Whether or not to confirm additional changes. Immutable
    */
    static
    bool isAskChangesImmutable()
    {
      return self()->isImmutable( QStringLiteral( "AskChanges" ) );
    }

    /**
      Set Show foreign architecture packages also available natively.
    */
    static
    void setShowMultiArchDupes( bool v )
    {
      if (!self()->isShowMultiArchDupesImmutable())
        self()->mShowMultiArchDupes = v;
    }

    /**
      Get Show foreign architecture packages also available natively.
    */
    static
    bool showMultiArchDupes()
    {
      return self()->mShowMultiArchDupes;
    }

    /**
      Is Show foreign architecture packages also available natively. Immutable
    */
    static
    bool isShowMultiArchDupesImmutable()
    {
      return self()->isImmutable( QStringLiteral( "ShowMultiArchDupes" ) );
    }

    /**
      Set Status of columns in the manager list of packages.
    */
    static
    void setManagerListColumns( const QString & v )
    {
      if (!self()->isManagerListColumnsImmutable())
        self()->mManagerListColumns = v;
    }

    /**
      Get Status of columns in the manager list of packages.
    */
    static
    QString managerListColumns()
    {
      return self()->mManagerListColumns;
    }

    /**
      Is Status of columns in the manager list of packages. Immutable
    */
    static
    bool isManagerListColumnsImmutable()
    {
      return self()->isImmutable( QStringLiteral( "ManagerListColumns" ) );
    }

    /**
      Set Status of columns in the changes review list of packages.
    */
    static
    void setReviewListColumns( const QString & v )
    {
      if (!self()->isReviewListColumnsImmutable())
        self()->mReviewListColumns = v;
    }

    /**
      Get Status of columns in the changes review list of packages.
    */
    static
    QString reviewListColumns()
    {
      return self()->mReviewListColumns;
    }

    /**
      Is Status of columns in the changes review list of packages. Immutable
    */
    static
    bool isReviewListColumnsImmutable()
    {
      return self()->isImmutable( QStringLiteral( "ReviewListColumns" ) );
    }

    /**
      Set Use supplemental slow search when xapian search is not available.
    */
    static
    void setUseSlowSearch( bool v )
    {
      if (!self()->isUseSlowSearchImmutable())
        self()->mUseSlowSearch = v;
    }

    /**
      Get Use supplemental slow search when xapian search is not available.
    */
    static
    bool useSlowSearch()
    {
      return self()->mUseSlowSearch;
    }

    /**
      Is Use supplemental slow search when xapian search is not available. Immutable
    */
    static
    bool isUseSlowSearchImmutable()
    {
      return self()->isImmutable( QStringLiteral( "UseSlowSearch" ) );
    }

    /**
      Set Show confirmation dialog when quitting with pending changes.
    */
    static
    void setConfirmOnQuit( bool v )
    {
      if (!self()->isConfirmOnQuitImmutable())
        self()->mConfirmOnQuit = v;
    }

    /**
      Get Show confirmation dialog when quitting with pending changes.
    */
    static
    bool confirmOnQuit()
    {
      return self()->mConfirmOnQuit;
    }

    /**
      Is Show confirmation dialog when quitting with pending changes. Immutable
    */
    static
    bool isConfirmOnQuitImmutable()
    {
      return self()->isImmutable( QStringLiteral( "ConfirmOnQuit" ) );
    }

    /**
      Set Custom colors for status column in format "status:color;status:color".
    */
    static
    void setStatusColumnColors( const QString & v )
    {
      if (!self()->isStatusColumnColorsImmutable())
        self()->mStatusColumnColors = v;
    }

    /**
      Get Custom colors for status column in format "status:color;status:color".
    */
    static
    QString statusColumnColors()
    {
      return self()->mStatusColumnColors;
    }

    /**
      Is Custom colors for status column in format "status:color;status:color". Immutable
    */
    static
    bool isStatusColumnColorsImmutable()
    {
      return self()->isImmutable( QStringLiteral( "StatusColumnColors" ) );
    }

    /**
      Set Show installed and available version columns by default.
    */
    static
    void setShowVersionColumns( bool v )
    {
      if (!self()->isShowVersionColumnsImmutable())
        self()->mShowVersionColumns = v;
    }

    /**
      Get Show installed and available version columns by default.
    */
    static
    bool showVersionColumns()
    {
      return self()->mShowVersionColumns;
    }

    /**
      Is Show installed and available version columns by default. Immutable
    */
    static
    bool isShowVersionColumnsImmutable()
    {
      return self()->isImmutable( QStringLiteral( "ShowVersionColumns" ) );
    }

    /**
      Set Path to local .deb folder for offline package installation.
    */
    static
    void setLocalDebFolder( const QString & v )
    {
      if (!self()->isLocalDebFolderImmutable())
        self()->mLocalDebFolder = v;
    }

    /**
      Get Path to local .deb folder for offline package installation.
    */
    static
    QString localDebFolder()
    {
      return self()->mLocalDebFolder;
    }

    /**
      Is Path to local .deb folder for offline package installation. Immutable
    */
    static
    bool isLocalDebFolderImmutable()
    {
      return self()->isImmutable( QStringLiteral( "LocalDebFolder" ) );
    }

    /**
      Set List of package repositories.
    */
    static
    void setRepositories( const QStringList & v )
    {
      if (!self()->isRepositoriesImmutable())
        self()->mRepositories = v;
    }

    /**
      Get List of package repositories.
    */
    static
    QStringList repositories()
    {
      return self()->mRepositories;
    }

    /**
      Is List of package repositories. Immutable
    */
    static
    bool isRepositoriesImmutable()
    {
      return self()->isImmutable( QStringLiteral( "Repositories" ) );
    }

  protected:
    MuonSettings();
    friend class MuonSettingsHelper;


    // muon
    QList<int> mSplitterSizes;
    int mWidth;
    int mHeight;
    int mUndoStackSize;
    bool mAskChanges;
    bool mShowMultiArchDupes;
    QString mManagerListColumns;
    QString mReviewListColumns;
    bool mUseSlowSearch;
    bool mConfirmOnQuit;
    QString mStatusColumnColors;
    bool mShowVersionColumns;
    QString mLocalDebFolder;
    QStringList mRepositories;

  private:
};

#endif

